// Auto-generated by quantum_verilog_bridge.py
// Format: {q0, q1, ancilla, expected_q2}
// 4 bits per vector
0  // AND(0,0,anc=0) → 0
3  // NAND(0,0,anc=1) → 1
4  // AND(0,1,anc=0) → 0
7  // NAND(0,1,anc=1) → 1
8  // AND(1,0,anc=0) → 0
B  // NAND(1,0,anc=1) → 1
D  // AND(1,1,anc=0) → 1
E  // NAND(1,1,anc=1) → 0
